### ISSUE TITLE
Undefined Name

### ISSUE THREAD

**Issue by djankies** [Blue-Ocean-Group-1/flalingo#44]
The welcome message on dashboard may display undefined for the name. 
Expected edge case to be handled with default text
<img width="884" alt="Screenshot 2024-11-23 at 1 27 08 PM" src="https://github.com/user-attachments/assets/738ebb3f-f4c9-4612-b131-80ffc371dbf9">

**Comment by rpotter741** [comment]
Fixed! 

`  const makeGreeting = () => {
    let name = user.name;
    let greeting = greetings[user.activeLanguages[0]];
    if (name === undefined && greeting) {
      return greeting;
    }
    if (greeting === undefined && name) {
      return `Hello, ${name}`;
    }
    if (greeting && name) {
      return `${greeting}, ${name}`;
    }
    return 'Hello!';
  };`
