### ISSUE TITLE
Dashboard sections overlap

### ISSUE THREAD

**Issue by djankies** [Blue-Ocean-Group-1/flalingo#50]
**Expected**
Dashboard sections resize or break upon widow resize before overlapping occurs

**Actual**
Sections overlap

**Recreate**
Shrink window width

<img width="1154" alt="Screenshot 2024-11-23 at 2 04 36 PM" src="https://github.com/user-attachments/assets/81b78832-71d7-4233-8fec-6fd2e4ab453a">

**Comment by rpotter741** [comment]
Set a minimum width to component, preventing the overlap
