### ISSUE TITLE
Statistics becomes malformed after window resizing

### ISSUE THREAD

**Issue by djankies** [Blue-Ocean-Group-1/flalingo#56]
**Expected**
Graph responsive to size of window

**Actual**
Graph shrinks upon window width narrowing, but does not expand back

**Recreate**
Shrink window width, then expand window width

<img width="397" alt="Screenshot 2024-11-23 at 3 10 01 PM" src="https://github.com/user-attachments/assets/8d403d2e-7fb3-46fc-8838-280191fa1b47">

**Comment by rpotter741** [comment]
Added dynamic sizing to container and set canvas element to max height
